### ISSUE TITLE
quickFix broken in typescript 2.7.1

### ISSUE THREAD

**Issue by arznaar** [angelozerr/tslint-language-service#60]
After updating to the version 2.7.1 of typescript, most of the times i don't have quickFix bulb and shortcut doesn't work.

As you can see in image - cursor is on the issue that can be fixed via quickFix, but there is no bulb.
![image](https://user-images.githubusercontent.com/6916413/35812746-e4fa8806-0aa2-11e8-9fb3-97e4571fb785.png)

In typescript outpul log there is an error
```
[Info  - 6:37:02 PM] Started TSServer
[Error  - 6:37:05 PM] 'getCodeFixes' request failed with error.
Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getClass (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:77545:22)
    at c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:77533:46
    at Function.ChangeTracker.with (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:76425:17)
    at Object.getCodeActions (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:77532:64)
    at c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:77059:33
    at Object.forEach (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:1430:30)
    at Object.getFixes (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:77058:16)
    at c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:83206:35
    at Object.flatMap (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:1697:25)
    at Object.getCodeFixesAtPosition (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:83204:23)
    at Object.proxy.getCodeFixesAtPosition (c:\Users\s.kaptur\tslint-error\node_modules\tslint-language-service\out\src\index.js:334:31)
    at IOSession.Session.getCodeFixes (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:90228:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:89132:61)
    at c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:90393:88
    at IOSession.Session.executeWithRequestId (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:90384:28)
    at IOSession.Session.executeCommand (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:90393:33)
    at IOSession.Session.onMessage (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:90413:35)
    at Interface.<anonymous> (c:\Users\s.kaptur\tslint-error\node_modules\typescript\lib\tsserver.js:91614:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:191:7)
    at Interface._onLine (readline.js:241:10)
    at Interface._normalWrite (readline.js:384:12)
    at Socket.ondata (readline.js:101:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

Repo where i reproduced it: https://github.com/arznaar/tls-error

Current versions:
* typescript version - 2.7.1
* tslint version - 5.9.1
* tslint-language-service version - 0.9.8

May be helpful:
* vscode version - 1.19.3
* vscode typescript version - 2.6.2

UPD: I can still reproduce it after today's vscode update to versions:
* vscode version - 1.20.0
* vscode typescript version - 2.7.1

**Comment by MartynasZilinskas** [comment]
Can confirm, reverting typescript to `2.6.2` quickFix started to work again.
Working dependencies:
```
        "tslint": "^5.9.1",
        "tslint-language-service": "^0.9.8",
        "typescript": "2.6.2"
```
